version: '3.8'

services:
  athena-feedback-explorer:
    build:
      context: .
      dockerfile: Dockerfile
    image: athena-feedback-explorer:latest
    container_name: athena-feedback-explorer
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount a local directory for custom feedback data
      # - ./data:/usr/share/nginx/html/data
    networks:
      - athena-network

networks:
  athena-network:
    driver: bridge