version: '3.8'

services:
  owui-feedback:
    build:
      context: .
      dockerfile: Dockerfile
    image: owui-feedback:latest
    container_name: owui-feedback
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount a local directory for custom feedback data
      # - ./data:/usr/share/nginx/html/data
    networks:
      - owui-network

networks:
  owui-network:
    driver: bridge